# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cibus' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cibus
  pod 'Alamofire', '~> 4.5'
  pod 'SwiftyJSON'

  target 'CibusTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CibusUITests' do
    inherit! :search_paths
    # Pods for testing
  end
end
